login: &login
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  database: phoenix_message_development
  <<: *login

test: &test
  database: phoenix_message_test
  <<: *login

cucumber:
  <<: *test

production:
  database: phoenix_message_production
  <<: *login

staging:
  database: phoenix_message_staging
  <<: *login
