import { schema } from 'normalizr';

export const widget = new schema.Entity('widget');

export const ADD_WIDGET = 'ADD_WIDGET';
export const UPDATE_WIDGET = 'UPDATE_WIDGET';
export const REMOVE_WIDGET = 'REMOVE_WIDGET';

export const REQUEST_CREATE_SHARED_MESSAGE = 'REQUEST_CREATE_SHARED_MESSAGE';
export const RECEIVE_CREATE_SHARED_MESSAGE = 'RECEIVE_CREATE_SHARED_MESSAGE';

export const REQUEST_SHOW_SHARED_MESSAGE = 'REQUEST_SHOW_SHARED_MESSAGE';
export const RECEIVE_SHOW_SHARED_MESSAGE = 'RECEIVE_SHOW_SHARED_MESSAGE';

export const REQUEST_MESSAGE_LIST = 'REQUEST_MESSAGE_LIST';
export const RECEIVE_MESSAGE_LIST = 'RECEIVE_MESSAGE_LIST';

export const REMOVE_WIDGET_FROM_MESSAGE = 'REMOVE_WIDGET_FROM_MESSAGE';
